### ISSUE TITLE
global: move from raven to sentry-python

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-logging#40]
The raven library for sending events to Sentry is deprecated and being replaced by the Sentry-SDK library.

- Add support for [sentry-sdk](https://pypi.org/project/sentry-sdk/).
- Backward compatibility for raven must be maintained.
- Add deprecation warning to Raven.
- Add documentation

**Comment by ntarocco** [comment]
From the Sentry documentation: https://docs.sentry.io/error-reporting/quickstart/?platform=python

**Comment by equadon** [comment]
We had some issues with Raven with warnings still going through to Sentry even with `LOGGING_SENTRY_PYWARNINGS` set to `False`.

I checked it out and found that Raven adds the `SentryHandler` to the root logger and since `logger.getLogger('py.warnings').propagate` is set to `True` it will propagate to its parent logger which is the root logger and run the `SentryHandler`. Raven supports excluding loggers from this behavior in https://github.com/getsentry/raven-python/blob/d891c20f0f930153f508e9d698d9de42e910face/raven/conf/__init__.py#L26 but I don't see any way to configure this other than subclassing the `Sentry` class in `raven.contrib.flask`.

Does it make sense to fix this or is it better to wait for the move to sentry-python?

**Comment by kasioumis** [comment]
This could be useful: https://forum.sentry.io/t/switching-to-sentry-python/4733

**Comment by lnielsen** [comment]
@roksys When you make a PR please add a release commit on top for v1.2.0
